### ISSUE TITLE
upload to OSHpark

### ISSUE THREAD

**Issue by sl1pkn07** [siddolo/3Dprinter-laser#1]
Hi. thanks for this wonderful project

i want craft the PCB throught OSHpark service

i can(with permission)/or you can upload the PCB to this service?

https://oshpark.com

greetings

**Comment by siddolo** [comment]
yes, for sure

**Comment by Haku73** [comment]
Hi,
I have a problem with my laser. When I plug it in, it always turn on. I checked and actually the PWM / TTL output modulates from 0 to 5V with the cooling fan. It's probably a problem with my laser [(this)](https://it.aliexpress.com/item/32367371022.html?spm=a2g0s.9042311.0.0.27424c4dlOAgxU). What could I feel? The same happens with the plotter on which it was mounted if I connect the USB power supply first. It may depend on the frequency of the TTL modulation?

Thanks
Andrea

**Comment by siddolo** [comment]
Hi Andrea,

check the JP1 fix: https://github.com/siddolo/3Dprinter-laser/blob/master/schematics.png
